server:
  port: 8000

spring:
  application:
    name: cambio-service

  kafka:
    auto-offset-reset: latest
    group-id: cambio-service
    max-poll-records: 500
    max-retry: 5

# Common Kafka Properties
auto:
  create:
    topics:
    enable: true

management:
  endpoints:
    web:
      exposure:
        include: health
        exclude: dev,beans,info
  endpoint:
    health:
      enabled: true
      status:
        order: UP,DOWN,OUT_OF_SERVICE,UNKNOWN

cache-timeout:
  default-ttl: -1
  caches-ttl:
    cambio-expire: 2