eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: cambio-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: rootroot

  redis:
    host: localhost
    port: 6379

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    schema-registry-url: "http://127.0.0.1:8081"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: cambio_service
    user: root
    password: rootroot
