server:
  port: 8000

spring:
  application:
    name: cambio-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: rootroot

  redis:
    host: localhost
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health
        exclude: dev,beans,info
  endpoint:
    health:
      enabled: true
      status:
        order: UP,DOWN,OUT_OF_SERVICE,UNKNOWN

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: cambio_service
    user: root
    password: rootroot

cache-timeout:
  default-ttl: -1
  caches-ttl:
    cambio-expire: 2